### ISSUE TITLE
Feature : Customising the used ServiceAccount (custom serviceAccountName)

### ISSUE THREAD

**Issue by PaulEvans8669** [OctoPerf/helm-charts#13]
Hello,

I am currently facing an issue where the serviceAccount is not configurable in the Helm Chart for the backend StatefulSet template, and thus preventing me from tweaking my configuration. My goal here is to add an init countainer pulling my license key from a cloud vault instead of having it in the `backend.licenseFile` field.

The currently generated pods managed by the StatefulSet use the `default` serviceAccount.

Having the possibility to insert a custom value in the `spec.template.spec.serviceAccountName` field would be a very nice feature.

Thank you for your help.

**Comment by jloisel** [comment]
Hi,

Could you clarify the changes we need to make on our side?

Thanks!

**Comment by PaulEvans8669** [comment]
Hello,

Adding a variable in the templates/values files would give us the possibility to override the `default` service account.

Here is an example in the prometheus helm chart repository : https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/deploy.yaml#L48C18-L48C18

**Comment by jloisel** [comment]
Could you make a PR or explain precisely what needs to be modified? I'm not sure to fully understand what needs to be added here.

**Comment by jloisel** [comment]
Done, added configurable service account name to backend statefulset. Released in Helm Chart 13.2.4.
