### ISSUE TITLE
Impossible to add a volumeMount

### ISSUE THREAD

**Issue by PaulEvans8669** [OctoPerf/helm-charts#14]
Hello,

We are currently facing an issue where we are unable to add custom volume mounts. The statefullset template includes the following line :
`{{- toYaml .Values.backend.volumeMounts . | nindent 8 }}` However toYaml only takes 1 parameter (the Values path), and is provided 2 (Valuespath + "." ), throwing an error when trying to mount a volume.

**Comment by jloisel** [comment]
Hi,

Should we change:

```
{{- toYaml .Values.backend.volumeMounts . | nindent 8 }}
```

to this:

```
{{- toYaml .Values.backend.volumeMounts | nindent 8 }}
```

**Comment by PaulEvans8669** [comment]
Hello,

Absolutely! :)
