### ISSUE TITLE
Adding fully customizable enviroment variables

### ISSUE THREAD

**Issue by PaulEvans8669** [OctoPerf/helm-charts#15]
Hello,

We are currently trying to use otka for authentication, but are facing an issue where our client id and client secret is not hidden in the values.yaml file (backend.applicationYml), thus preventing us from versioning it to some extent.

Being able to add a secret reference to the env, custom key/value pairs, or even a custom yaml value to the env stanza of the statefullset would be a huge improvement in this chart. 

Thank you for your help

**Comment by jloisel** [comment]
Hi,

You can use environment variables via `backend.env`. Would it be enough? You also have "secretMounts".

**Comment by PaulEvans8669** [comment]
Hi,

Using `backend.env` wasn't a solution for us, as it add values to a configMap, not giving us the possibility to point to a secret using the `envFrom` option. 

If I remember correctly, using `secretMounts` wasn't a solution as we want to add a value to the app config file. So adding another file next to the main config file wouldn't work as it wouldn't be loaded by the app.

We wanted to use environment variables to try and override the app config file values (especially the license key).

**Comment by jloisel** [comment]
license key can only be provided through a file named "license.l4j" mounted on "/home/octoperf/license/license.l4j" path inside the container. So it's not possible to pass it using an environment variable.
