### ISSUE TITLE
Done as in PR and released.

### ISSUE THREAD

**Issue by QDudouet** [OctoPerf/helm-charts#18]
Done as in PR and released.

_Originally posted by @jloisel in https://github.com/OctoPerf/helm-charts/issues/17#issuecomment-1695825049_
           
It seems that the problem still exists in version 13.2.1 of kubernetes-agent.
The Valuespath + "." part mentioned [here in issue 14](https://github.com/OctoPerf/helm-charts/issues/14)  is available for lines with 'toYaml'. 
On deployment.yaml you use 'tpl' that need 2 arguments, then the Valuespath + "." should stay on version 13.2.1 for deployment.yaml file.

For example :
v13.2.0 ===> volumeMounts: {{ tpl .Values.volumeMounts . | nindent 10 }}
v13.2.1 ===> volumeMounts: {{ tpl .Values.volumeMounts | nindent 10 }} Dot is missing

Maybe a fix is ​​planned for v14.0.0 of the agent ?

**Comment by jloisel** [comment]
Can you please make a pull request to fix the issue? I'm not sure to understand what you mean.

**Comment by jloisel** [comment]
Done in deployment:

```yaml
        volumeMounts: {{ toYaml .Values.volumeMounts | nindent 10 }}
```

**Comment by jloisel** [comment]
Republished 14.1.0 helm chart.
