### ISSUE TITLE
cannot edit backend pod annotations

### ISSUE THREAD

**Issue by QDudouet** [OctoPerf/helm-charts#20]
Hello

As part of the upgrade to your version 15.1.0 we are taking the opportunity to facilitate the integration of the OpenTelemetry operator. 
To enable a better implementation, we need to be able to add annotations specific to the backend pod, and for the moment the solution of your StatefulSet only allows you to overload the annotations of the SFS and not of the pod: 

```
  annotations:
  {{- with .Values.backend.annotations }}
  {{- toYaml . | nindent 4 }}
  {{-end}}
```

I imagine that a solution of this type added to the SFS Backend would be sufficient:

```
spec:
  template:
    metadata:
      annotations:
        {{- with .Values.backend.podAnnotations }}
	{{- toYaml . | nindent 8}}
	{{- end }}

```

Do you think you can make this editable in a near release?

Sincerely,

**Comment by jloisel** [comment]
Hi, I'm looking into this.

**Comment by jloisel** [comment]
Done in version 15.2.1. Can you please confirm it's working for you?

**Comment by QDudouet** [comment]
The solution provided is fully functional in version 15.2.1 of the chart, thank you!
