### ISSUE TITLE
frontend-dep.yaml references an unknown volume "nginx-template"

### ISSUE THREAD

**Issue by rodriguezc** [OctoPerf/helm-charts#8]
Helm install fails with the following error because of an undeclared volume "nginx-template".
```
Error: INSTALLATION FAILED: Deployment.apps "octoperf-enterprise-edition-frontend" is invalid: spec.template.spec.containers[0].volumeMounts[1].name: Not found: "nginx-template"
```
See
https://github.com/OctoPerf/helm-charts/blob/93711c298183d2319573ebce687178e370c467ab/enterprise-edition/templates/frontend/frontend-dep.yaml#L49
and 
https://github.com/OctoPerf/helm-charts/blob/93711c298183d2319573ebce687178e370c467ab/enterprise-edition/templates/frontend/frontend-dep.yaml#L67

**Comment by jloisel** [comment]
Thanks, we're looking into it :)
