### ISSUE TITLE
Wrong indent in backend.volumes

### ISSUE THREAD

**Issue by rodriguezc** [OctoPerf/helm-charts#9]
backend/statefulset.yaml allows to declare volumes but indent is wrong: 8 instead of 6.
This parameter break the helm template build because next declarations of volumes have an indent of 6.
So the final volumes list end up with different indent

https://github.com/OctoPerf/helm-charts/blob/master/enterprise-edition/templates/backend/statefulset.yaml#L63

https://github.com/OctoPerf/helm-charts/blob/master/enterprise-edition/templates/backend/statefulset.yaml#L66

**Comment by rodriguezc** [comment]
Same issue with volumeMounts

**Comment by jloisel** [comment]
Thx for reporting, fixed in Chart version 13.1.1 (13.0.0 app).
